In [ ]:
!pip install pyod
! pip install xgboost
! pip install imblearn
from imblearn.over_sampling import SMOTE, ADASYN
import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns
from fastai.tabular.all import df_shrink
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold, cross_val_score
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score,KFold
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score, GridSearchCV, RandomizedSearchCV
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.svm import SVC


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.4/153.4 kB 3.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pyod: filename=pyod-1.1.0-py3-none-any.whl size=185329 sha256=e6d39e265645b4fc506f3d12e04a3124d91de471c61be901d646a78edfba41e7
  Stored in directory: /root/.cache/pip/wheels/36/8e/e2/e932956b10b843eb6be9eefa70b5c1bee7b561be14c423b136
Successfully built pyod


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%cd /content/drive/MyDrive/capstone project

/content/drive/MyDrive/capstone project


In [ ]:
df = pd.read_csv("TON_IOT_pre.unknown")

In [ ]:
print(df.shape)
df.head()

(1210789, 20)


L4_SRC_PORT  L4_DST_PORT  PROTOCOL  L7_PROTO  IN_BYTES  OUT_BYTES  IN_PKTS  \
0        63318          443         6     91.00       181        165        2   
1        57442        15600        17      0.00        63          0        1   
2        57452        15600        17      0.00        63          0        1   
3        51989        15600        17      0.00        63          0        1   
4        53927         1900        17    153.12       459          0        3   

   OUT_PKTS  TCP_FLAGS  FLOW_DURATION_MILLISECONDS  Label  Attack  \
0         1         24                         327      0  Benign   
1         0          0                           0      0  Benign   
2         0          0                           0      0  Benign   
3         0          0                           0      0  Benign   
4         0          0                         614      0  Benign   

   IPV4_SRC_ADDR_0  IPV4_SRC_ADDR_1  IPV4_SRC_ADDR_2  IPV4_SRC_ADDR_3  \
0              192              168                1              195   
1              192              168                1               79   
2              192              168                1               79   
3              192              168                1               79   
4              192              168                1                6   

   IPV4_DST_ADDR_0  IPV4_DST_ADDR_1  IPV4_DST_ADDR_2  IPV4_DST_ADDR_3  
0               52              139              250              253  
1              192              168                1              255  
2              239              255              255              250  
3              192              168                1              255  
4              239              255              255              250

In [ ]:
X = df.drop(['Label','Attack'],axis=1)
y = df['Label']

X_test = df.drop(['Label','Attack'],axis=1)
y_test = df['Label']
X=pd.get_dummies(X,drop_first=True)
X_test = pd.get_dummies(X_test,drop_first=True)
oversample = SMOTE()

In [ ]:
X, y = oversample.fit_resample(X, y)
label_encoder = preprocessing.LabelEncoder()
scaler=preprocessing.StandardScaler()


In [ ]:
X=scaler.fit_transform(X)
X_test=scaler.fit_transform(X_test)

y= label_encoder.fit_transform(y)
y_test = label_encoder.fit_transform(y_test)



In [ ]:
from numpy import mean
from numpy import std
# prepare the cross-validation procedure
cv = KFold(n_splits=5, random_state=1, shuffle=True)
# create model
model_2 = RandomForestClassifier(random_state = 1099)
# evaluate model
scores = cross_val_score(model_2, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

Accuracy: 1.000 (0.000)


In [ ]:
scores

array([0.99993488, 0.99993488, 0.99992486, 0.99993237, 0.99992987])

In [ ]:
model_1.fit(X,y)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
score=cross_val_score(model_1,X,y,cv=kfold)
print("Cross Validation Scores are {}".format(score))
print("Average Cross Validation score :{}".format(score.mean()))

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

Cross Validation Scores are [0.99558468 0.99556213 0.99549   ]
Average Cross Validation score :0.9955456034625269


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
score

array([0.99558468, 0.99556213, 0.99549   ])

In [ ]:
# Define the search space

param_grid = {
    'penalty': ['l1','l2'], 'C': [0.001,0.01,0.1,1,10,100,1000]
    }
# Set up score
scoring = ['recall']
# Set up the k-fold cross-validation
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
model_1= LogisticRegression()
grid_search = GridSearchCV(estimator=model_1,
                           param_grid=param_grid,
                           cv=kfold,
                           verbose=0)
# Fit grid search
grid_result = grid_search.fit(X, y)

grid_search.fit(X,y)
y_pred = grid_search.predict(X_test)
print(classification_report(y_test,y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

              precision    recall  f1-score   support

           0       0.36      1.00      0.52    212674
           1       1.00      0.61      0.76    998115

    accuracy                           0.68   1210789
   macro avg       0.68      0.81      0.64   1210789
weighted avg       0.89      0.68      0.72   1210789



In [ ]:
model_1.fit(X,y)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
score=cross_val_score(model_1,X,y,cv=kfold)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [ ]:
score

array([0.99572444, 0.99564178, 0.99557917, 0.99562676, 0.99536126])

In [ ]:
# xgboost
from numpy import mean
from numpy import std
# prepare the cross-validation procedure
cv = KFold(n_splits=5, random_state=1, shuffle=True)
# create model
model_3= XGBClassifier(learning_rate=0.02, n_estimators=600)
# evaluate model
scores = cross_val_score(model_3, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

Accuracy: 1.000 (0.000)


In [ ]:
scores

array([0.99993237, 0.99993488, 0.99991734, 0.99992736, 0.99992235])